paths:
  /user/email-send/{emailId}:
    get:
      tags:
        - User
      summary: Send Email to User
      description: Send Email to User.
      operationId: UserController.emailSend
      parameters:
        - in: path
          name: emailId
          description: EmailId
          required: true
          schema:
            type: string # Fixed 'type' from 'email'
      responses:
        200:
          description: Email Sent Successfully.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"

  /login:
    post:
      tags:
        - User
      summary: User Login
      description: Authenticate user with username and password.
      operationId: UserController.login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                  description: User's username.
                password:
                  type: string
                  description: User's password.
      responses:
        "200":
          description: User authenticated successfully.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/successRes"
        "401":
          description: Unauthorized. Invalid credentials.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorRes"

components:
  schemas:
    User:
      type: object
      properties:
        statuscode:
          type: integer
          format: int64
        message:
          type: string
        data:
          type: object
    errorRes:
      type: object
      properties:
        statuscode:
          type: integer
          format: int64
          example: 0
        message:
          type: string
    successRes:
      type: object
      properties:
        statuscode:
          type: integer
          format: int64
          example: 1
        message:
          type: string
        data:
          type: object
